[package]
name = "impp"
version = "0.3.0"
authors = ["mad-de"]
edition = "2018"

[dependencies]
ureq = "0.11"
rand = "0.7"
regex = "1"
preferences = "1.1"
openssl = { version = "0.10", features = ["vendored"] }
